### ISSUE TITLE
무중단 배포 구현

### ISSUE THREAD

**Issue by zxcv9203** [prgrms-web-devcourse/Team-Books-CheckMoi-BE#184]
### 🧑‍💻 추가할 기능 설명
운영 서버에 대해서 Blue Green 배포 방법을 사용하여 무중단 배포 구현

**Comment by zxcv9203** [comment]
무중단 배포 구현 완료

**Comment by kimziou77** [comment]
dev 서버도 무중단인가요?!

**Comment by kimziou77** [comment]
dev 서버도 무중단인가요?!

**Comment by zxcv9203** [comment]
dev서버 무중단 배포 완료

**Comment by kimziou77** [comment]
😺😺😺😺 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🔥 🔥 🔥😺😺😺😺 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🔥 🔥 🔥우왕 😺😺😺😺 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🔥 🔥 🔥
