### ISSUE TITLE
스터디 신청 validation 추가

### ISSUE THREAD

**Issue by zxcv9203** [prgrms-web-devcourse/Team-Books-CheckMoi-BE#217]
### 🧑‍💻 추가할 기능 설명
- [x] 스터디 모집중에만 스터디를 신청할 수 있다
- [x] maxParticipant 도달시 신청 못한다
- [x] #223

다음 API에 대해서 validation 로직 추가
`PUT /api/studies/{studyId}/members`

**Comment by kimziou77** [comment]
사용자가 가입한 스터디가 10개 이상이면 가입을 할 수 없다
