### ISSUE TITLE
스터디 조회 이슈

### ISSUE THREAD

**Issue by kimziou77** [prgrms-web-devcourse/Team-Books-CheckMoi-BE#250]
### ⚠️ 버그 요약
피카츄 스터디 실종문제
프론트에서 v1 api를 호출하는데, 이상동작이 확인됨

GET /api/studies
피카츄 스터디는 현재 4개가 존재하는데
한개만 나오는 문제

원하는 결과 
![image](https://user-images.githubusercontent.com/41179265/184547352-0d6cff39-9b05-4a39-92f8-371366e0223b.png)

### 💀 에러 발생 상황

![image](https://user-images.githubusercontent.com/41179265/184547268-8fcf1dbd-9479-4d1c-936d-4d7ccf014ebd.png)

![image](https://user-images.githubusercontent.com/41179265/184547260-58e681fe-d595-47fb-b344-7a180b39624f.png)

### 🏔️ 환경
- OS: [e.g. Windows]

**Comment by zxcv9203** [comment]
해당 API는 모집중인 스터디만 전달하기 때문에 의도에 맞게 동작하고 있습니다.
