### ISSUE TITLE
나의 스터디 목록 확인

### ISSUE THREAD

**Issue by zxcv9203** [prgrms-web-devcourse/Team-Books-CheckMoi-BE#42]

**Comment by kimziou77** [comment]
![image](https://user-images.githubusercontent.com/41179265/182031197-e660ab4c-2b0e-4dae-8247-f2649657c161.png)
해당 부분에 대한 부분 회원 조회시 같이 진행 되어서 -> 기존에 작업 수정으로 새 이슈 제작
