### ISSUE TITLE
스터디 엔티티에서 스터디 멤버에 대한 카운트 쿼리가 집계되지 않는 현상

### ISSUE THREAD

**Issue by zxcv9203** [prgrms-web-devcourse/Team-Books-CheckMoi-BE#50]
### 💀 에러 발생 상황
스터디 엔티티에서 스터디 멤버에 대한 카운트 쿼리를 추가하여 DB에서 불러올때마다 최신화 되도록 구현했지만 쿼리는 실제로 날아가지만 집계되지 않는 현상이 발생했습니다.

### 🖥️ 발생 화면
<img width="620" alt="image" src="https://user-images.githubusercontent.com/41960243/182046897-7d64dd0f-bbdd-4da7-9340-f22b16230b27.png">

### 🏔️ 환경
- OS: MAC OS

**Comment by kimziou77** [comment]
💀

**Comment by zxcv9203** [comment]
실제 서버에서 테스트 했을때 문제 없이 동작했습니다 영속성 컨텍스트 관련문제로 파악되었습니다.
